export const app = {
  OTP_VALIDTIME: 90000,
  EXPIRE_DURATIONMINUTE: 60,
  BLIND_MISSED: 1,
  BONUSEXPIRE_PERIOD_INDAYS: 30,
  PERCENTFOR_BONUSRELEASE: 100,
  HANDTAB_RECORD_COUNT: 3,
  ALLOWED_IMAGES_TYPE: ['png', 'jpg', 'jpeg'],
  GAME_NAME_TEXT: 'Poker Moogley',
};
