import { app } from './app';

const tableSpeed = {
  hyperturbo: 'HYPERTURBO',
  turbo: 'TURBO',
  medium: 'MEDIUM',
  standard: 'STANDARD',
};

const tableSpeedFromTurnTime = {
  [tableSpeed.hyperturbo]: 10,
  [tableSpeed.turbo]: 15,
  [tableSpeed.medium]: 20,
  [tableSpeed.standard]: 30,
};

const turnTimeFromSpeed = {
  [tableSpeedFromTurnTime[tableSpeed.hyperturbo]]: tableSpeed.hyperturbo,
  [tableSpeedFromTurnTime[tableSpeed.turbo]]: tableSpeed.turbo,
  [tableSpeedFromTurnTime[tableSpeed.medium]]: tableSpeed.medium,
  [tableSpeedFromTurnTime[tableSpeed.standard]]: tableSpeed.standard,
};

export const stateOfX = {
  gameDetails: { name: app.GAME_NAME_TEXT },
  OFCstartGameEvent: {
    sit: 'PLAYERSIT',
    gameOver: 'GAMEOVER',
    addPoints: 'ADDPINTS',
  },
  startGameEvent: {
    sit: 'PLAYERSIT',
    gameOver: 'GAMEOVER',
    resume: 'RESUME',
    addChips: 'ADDCHIPS',
    tournament: 'TOURNAMENT',
    tournamentAfterBreak: 'TOURNAMENTAFTERBREAK',
  },
  startGameEventOnChannel: {
    idle: 'IDLE',
    starting: 'STARTING',
    running: 'RUNNING',
  },
  gameState: {
    idle: 'IDLE',
    starting: 'STARTING',
    running: 'RUNNING',
    gameOver: 'GAMEOVER',
  },
  ofcGameState: {
    idle: 'IDLE',
    starting: 'STARTING',
    running: 'RUNNING',
    gameOver: 'GAMEOVER',
  },
  playerState: {
    waiting: 'WAITING',
    playing: 'PLAYING',
    outOfMoney: 'OUTOFMONEY',
    onBreak: 'ONBREAK',
    disconnected: 'DISCONNECTED',
    onleave: 'ONLEAVE',
    reserved: 'RESERVED',
    surrender: 'SURRENDER',
  },
  tableSpeed,
  tableSpeedFromTurnTime,
  turnTimeFromSpeed,
  extraTimeBank: {
    [tableSpeedFromTurnTime[tableSpeed.hyperturbo]]: 10,
    [tableSpeedFromTurnTime[tableSpeed.turbo]]: 15,
    [tableSpeedFromTurnTime[tableSpeed.medium]]: 20,
    [tableSpeedFromTurnTime[tableSpeed.standard]]: 30,
    default: 20,
  },
  round: {
    holeCard: 'HOLE CARDS',
    preflop: 'PREFLOP',
    flop: 'FLOP',
    turn: 'TURN',
    river: 'RIVER',
    showdown: 'SHOWDOWN',
  },
  roundToValue: {
    'HOLE CARDS': 0,
    PREFLOP: 1,
    FLOP: 2,
    TURN: 3,
    RIVER: 4,
    SHOWDOWN: 5,
  },
  ofcRound: {
    one: 'ONE',
    two: 'TWO',
    three: 'THREE',
    four: 'FOUR',
    five: 'FIVE',
    finished: 'FINISHED',
  },
  totalOFCround: 5,
  OFCplayerCards: { ONE: 5, TWO: 3, THREE: 3, FOUR: 3, FIVE: 3 },
  OFCplayerCardsInRound: { ONE: 5, TWO: 7, THREE: 9, FOUR: 11, FIVE: 13 },
  nextOFCroundOf: {
    ONE: 'TWO',
    TWO: 'THREE',
    THREE: 'FOUR',
    FOUR: 'FIVE',
    FIVE: 'FINISHED',
  },
  ofcTableSpeed: {
    hyperturbo: 'HYPERTURBO',
    turbo: 'TURBO',
    medium: 'MEDIUM',
    standard: 'STANDARD',
  },
  ofcTableSpeedFromTurnTime: {
    HYPERTURBO: 10,
    TURBO: 15,
    MEDIUM: 20,
    STANDARD: 30,
  },
  playerType: {
    dealer: 'DEALER',
    smallBlind: 'SMALLBLIND',
    bigBlind: 'BIGBLIND',
    straddle: 'STRADDLE',
  },
  endingType: {
    gameComplete: 'GAMECOMPLETED',
    everybodyPacked: 'EVERYBODYPACKED',
    onlyOnePlayerLeft: 'ONLYONEPLAYERLEFT',
  },
  dealerChatReason: {
    GAMECOMPLETED: 'GAMECOMPLETED',
    EVERYBODYPACKED: 'Every Body Else Folded',
    ONLYONEPLAYERLEFT: 'Every One Else Left',
  },
  ofcEndingType: {
    gameComplete: 'GAMECOMPLETED',
    allPlayerFouled: 'ALLPLAYERFOULED',
  },
  moves: ['CHECK', 'CALL', 'BET', 'RAISE', 'ALLIN', 'FOLD'],
  move: {
    check: 'CHECK',
    call: 'CALL',
    bet: 'BET',
    raise: 'RAISE',
    allin: 'ALLIN',
    fold: 'FOLD',
    standup: 'STANDUP',
    leave: 'LEAVE',
  },
  playerPrecheckValue: {
    CALL: 'Call',
    CALL_ANY: 'CallAny',
    FOLD: 'Fold',
    CHECK: 'Check',
    ALLIN: 'AllIn',
    CHECK_FOLD: 'Check_Fold',
    CALL_ANY_CHECK: 'CallAny_Check',
    NONE: 'NONE',
  },
  OFCmove: {
    submit: 'SUBMIT',
    discard: 'DISCARD',
    standup: 'STANDUP',
    leave: 'LEAVE',
  },
  delaerChatMove: {
    CHECK: 'Checks',
    CALL: 'Calls',
    BET: 'Bets',
    RAISE: 'Raises',
    ALLIN: 'All In',
    FOLD: 'Folds',
  },
  moveValue: { check: 1, call: 2, bet: 3, raise: 4, allin: 5, fold: 6 },
  preCheck: { setOne: 1, setTwo: 2, setThree: 3 },
  channelVariation: {
    holdem: 'Texas Hold’em',
    omaha: 'Omaha',
    omahahilo: 'Omaha Hi-Lo',
    ofc: 'Open Face Chinese Poker',
  },
  nextRoundOf: {
    PREFLOP: 'FLOP',
    FLOP: 'TURN',
    TURN: 'RIVER',
    RIVER: 'SHOWDOWN',
  },
  previousRoundOf: {
    PREFLOP: null,
    FLOP: 'PREFLOP',
    TURN: 'FLOP',
    RIVER: 'TURN',
    SHOWDOWN: 'RIVER',
  },
  totalPlayerCards: { 'Texas Hold’em': 2, Omaha: 4, 'Omaha Hi-Lo': 4 },
  totalCommunityCard: { PREFLOP: 0, FLOP: 3, TURN: 4, RIVER: 5, SHOWDOWN: 5 },
  issueStatus: { open: 'OPEN', close: 'CLOSE', process: 'PROCESS' },
  serverLogType: {
    info: 'INFO',
    warning: 'WARNING',
    error: 'ERROR',
    anonymous: 'ANONYMOUS',
    request: 'REQUEST',
    response: 'RESPONSE',
    broadcast: 'BROADCAST',
    dbQuery: 'DBQUERY',
  },
  serverType: {
    database: 'DATABASE',
    connector: 'CONNECTOR',
    gate: 'GATE',
    auth: 'AUTH',
    shared: 'SHARED',
  },
  logEvents: {
    joinChannel: 'JOINCHANNEL',
    reserved: 'RESERVED',
    sit: 'SIT',
    tableInfo: 'TABLEINFO',
    startGame: 'STARTGAME',
    playerTurn: 'PLAYERTURN',
    leave: 'LEAVE',
    roundOver: 'ROUNDOVER',
    gameOver: 'GAMEOVER',
    summary: 'SUMMARY',
    playerRoyality: 'OFCROYALITY',
  },
  profile: {
    category: {
      profile: 'PROFILE',
      transaction: 'TRANSACTION',
      game: 'GAME',
      tournament: 'TOURNAMENT',
      lobby: 'LOBBY',
      gamePlay: 'GAMEPLAY',
    },
    subCategory: {
      login: 'LOGIN',
      signUp: 'SIGNUP',
      update: 'UPDATE',
      emailVerify: 'EMAILVERIFY',
      password: 'PASSWORD',
      otp: 'OTP',
      freeChips: 'FREECHIPS',
      withdraw: 'WITHDRAW',
      recharge: 'RECHARGE',
      action: 'ACTION',
      winner: 'WINNER',
      participated: 'PARTICIPATED',
    },
    activityStatus: {
      progress: 'PROGRESS',
      completed: 'COMPLETED',
      error: 'ERROR',
    },
  },
  gameActivity: {
    category: { game: 'GAME', tournament: 'TOURNAMENT', gamePlay: 'GAMEPLAY' },
  },
  transaction: { subCategory: { transaction1: 'TRANSACTION1' } },
  gamePlay: {
    subCategory: {
      startGame: 'START GAME',
      leave: 'PLAYER LEFT',
      sit: 'PLAYER SIT',
      move: 'PLAYER MOVE',
      info: 'INFO',
      gameOver: 'GAME OVER',
    },
  },
  gameplay: {
    subCategory: {
      startGame: 'START GAME',
      leave: 'PLAYER LEFT',
      sit: 'PLAYER SIT',
      move: 'PLAYER MOVE',
      info: 'INFO',
      gameOver: 'GAME OVER',
    },
  },
  game: {
    subCategory: {
      startGame: 'START GAME',
      join: 'JOIN',
      sit: 'SIT',
      leave: 'LEAVE',
      move: 'MOVE',
      info: 'INFO',
      blindsAndStraddle: 'BLINDS AND STRADDLE',
      winner: 'WINNER',
      playerCards: 'PLAYER CARDS',
      playerState: 'PLAYER STATUS',
      playerChat: 'PLAYER CHAT',
      rakeDeduct: 'RAKE DEDUCT',
      runItTwice: 'RUN IT TWICE',
      sitoutNextHand: 'SIT OUT NEXT HAND',
      sitoutNextBigBlind: 'SIT OUT NEXT BIG BLIND',
      resetSitOut: 'RESET SIT OUT',
      resume: 'RESUME',
      addChips: 'ADD CHIPS',
      updateTableSettings: 'UPDATE TABLE SETTINGS(MUCK HAND)',
    },
  },
  tournament: {
    subCategory: { register: 'REGISTER', deRegister: 'DE-REGISTER' },
  },
  logType: {
    success: 'SUCCESS',
    error: 'ERROR',
    info: 'INFO',
    warning: 'WARNING',
  },
  gameType: { normal: 'NORMAL', tournament: 'TOURNAMENT' },
  tournamentState: {
    register: 'REGISTER',
    running: 'RUNNING',
    finished: 'FINISHED',
    upcoming: 'UPCOMING',
    cancelled: 'CANCELLED',
  },
  tournamentType: {
    sitNGo: 'SIT N GO',
    normal: 'NORMAL',
    satelite: 'SATELLITE',
  },
  role: {
    admin: 'admin',
    affiliate: 'affiliate',
    subaffiliate: 'sub-affiliate',
    user: 'user',
  },
  OFCevents: {
    makeMoveSuccess: 'MAKEMOVESUCCESS',
    makeMoveSuccessFail: 'MAKEMOVEFAIL',
    leaveSuccess: 'LEAVESUCCESS',
    autositSuccess: 'AUTOSITSUCCESS',
    addpointSuccess: 'ADDPOINTSUCCESS',
    sitSuccess: 'SITSUCCESS',
  },
  lobby: {
    subCategory: {
      fetchTables: 'FETCH TABLES',
      register: 'TOURNAMENT REGISTERATION',
    },
  },
  videoLogEventType: {
    broadcast: 'broadcast',
    response: 'response',
    gamePlayers: 'gamePlayers',
    joinResponse: 'joinResponse',
  },
  country: [{ name: 'India' }, { name: 'Nepal' }, { name: 'Bangladesh' }],
  MantisApi: 'http://192.168.2.35/mantis_api/mantisconnect_json.php',
  SendGridApiKey:
    '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',
  mailMessages: {
    from_email: undefined,
    mail_subjectAffiliate: 'your affiliate request is processed',
    mail_contentAffiliate:
      'Hello,Your request has been proceed. Admin will contact ASAP',
    mail_subjectAffiliateEdit: 'Affiliate profile update',
    mail_contentAffiliateEdit: 'Affiliate your profile has been updated',
    mail_subjectForgotPassword: 'Forgot Password Link',
    mail_contentForgotPassword: 'Click on given link to find your password',
    mail_subjectForgotPasswordDashboard: 'Resetting dashboard password',
    mail_contentForgotPasswordDashboard:
      'Click on given link to find your password',
    mail_subjectEmailVerification: 'Email Verification Link',
    mail_contentEmailVerification:
      'Click on the given link to verify your email ',
    mail_subjectDownloadApp: 'Download Atlas Poker App',
    mail_contentDownloadApp:
      'Hi, Thank you for chosing PokerMoogley to play poker. Please download Android build from below link undefined . Download our app now. ',
    mail_subjectScratchCardAffiliate: 'Scratch card (affiliate) of undefined',
    mail_subjectScratchCardPlayer: 'Scratch card for undefined',
    mail_scratchCardSender: 'rishabh@pokerMoogley.com',
    mail_subjectScratchcard: 'Create ScratchCard Link',
    from_emailAdmin: undefined,
    to_emailAdmin: undefined,
    mail_subjectAdmin: 'Affiliate Registration',
    mail_contentAdmin: 'An affiliate has been registered under you',
    from_emailUserSupport: undefined,
    mail_subjectAffiliateUserSupportSubject: 'User Support Desk',
    mail_contentAffiliateUserSupportContent: 'User Support Desk Content',
    from_emailLogin: undefined,
    subjectLogin: 'User Login',
    contentLogin: 'User Successfully logged in',
  },
  phoneMessages: {
    isSmsAllowedForScratch: false,
    sms_contentDownloadApp:
      'Hi, Thank you for chosing PokerSD to play poker. Please download Android build from below link undefined . Download our app now. ',
  },
  recordChange: {
    player: 'PLAYER',
    table: 'TABLE',
    tableNewValues: 'TABLENEWVALUES',
    tableViewNewPlayer: 'TABLEVIEWNEWPLAYER',
    tableViewLeftPlayer: 'TABLEVIEWLEFTPLAYER',
    tablePlayingPlayer: 'TABLEPLAYINGPLAYER',
    tableAvgPot: 'TABLEAVGPOT',
    tableFlopPercent: 'TABLEFLOPPERCENT',
    tableWaitingPlayer: 'TABLEWAITINGPLAYER',
    tableViewNewWaitingPlayer: 'TABLEVIEWNEWWAITINGPLAYER',
    tableViewChipsUpdate: 'TABLEVIEWCHIPSUPDATE',
    playerJoinTable: 'PLAYERJOINTABLE',
    sendStickerToPlayer: 'SENDSTICKERTOPLAYER',
    playerLeaveTable: 'PLAYERLEAVETABLE',
    onlinePlayers: 'ONLINEPLAYERS',
    tournamentEnrolledPlayers: 'TOURNAMENTTABLEENROLLED',
    tournamentStateChanged: 'TOURNAMENTSTATECHANGED',
    tournamentRankUpdate: 'TOURNAMENTRANKUPDATE',
    destroyTable: 'DESTROYTABLE',
    shufflePlayers: 'SHUFFLEPLAYERS',
    loyalityUpdate: 'LOYALITYUPDATE',
    tableViewLeftWaitingPlayer: 'TABLEVIEWLEFTWAITINGPLAYER',
    tournamentBlindChange: 'TOURNAMENTBLINDCHANGE',
    prizePool: 'PRIZEPOOL',
    tournamentActivePlayers: 'TOURNAMENTACTIVEPLAYERS',
    tournamentCancelled: 'TOURNAMENTCANCELLED',
    bountyChanged: 'BOUNTYCHANGED',
  },
  broadcasts: {
    tableUpdate: 'tableUpdate',
    updateProfile: 'updateProfile',
    tournamentTableUpdate: 'tableUpdate',
    playerUpdate: 'playerUpdate',
    tableView: 'tableView',
    joinTableList: 'joinTableList',
    sendStickerToPlayer: 'SENDSTICKERTOPLAYER',
    onlinePlayers: 'onlinePlayers',
    tournamentStateChange: 'tableUpdate',
    tournamentRankUpdate: 'tableView',
    tournamentLobby: 'tournamentLobby',
    tournamentCancelled: 'tournamentCancelled',
    antiBankingUpdatedData: 'antiBankingUpdatedData',
  },
  linkForAppDownload: 'http://www.pokersd.com',
};
